### ISSUE TITLE
Specify Paths to Config Files

### ISSUE THREAD

**Issue by CV8R** [Yetangitu/zmapi#2]
Would be great to be able to specify paths to config files instead of defaulting to user/.config

**Comment by Yetangitu** [comment]
You can already do that by setting XDG_CONFIG_HOME before invocation:

```
$ XDG_CONFIG_HOME=/tmp/config zmapi
configuration file (/tmp/config/zmapi/zmapi.conf) missing
new file created, edit it and restart program
```
The directory will be created if it does not exist (needs latest version of scripts which I just pushed to the repo)

Does this fit your scenario?

**Comment by CV8R** [comment]
That works, thanks.
